[package]
name = "uuid_router"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
serde = "1.0.219"
serde_json = "1.0.140"
once_cell = "1.19.0"
notify = "6.1.1"
tokio = { version = "1.0", features = ["full"] }
